[tool.poetry]
name = "organisms"
version = "0.1.0"
description = ""
authors = ["Jens van de Zande <jens.vandezande-acdt@asml.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
